import { useRouter } from 'expo-router';
import { useState } from 'react';
import { StyleSheet, Switch, Text, View } from 'react-native';
import { FigmaBack, FigmaScreen } from '@/src/components/figma-ui';
import { usePreferences } from '@/src/components/preferences-provider';
import { HapticPressable as Pressable } from '@/src/components/haptics';
import { colors, compactPressFeedback, navigationHeader } from '@/src/theme/tokens';
export default function Guide(){const router=useRouter();const{voiceEnabled,metronomeEnabled,hapticsEnabled,setVoiceEnabled,setMetronomeEnabled,setHapticsEnabled}=usePreferences();const[frequency,setFrequency]=useState(30);return <FigmaScreen><FigmaBack onPress={()=>router.back()}/><Text style={styles.header}>러닝 가이드 방식</Text><View style={styles.frequency}><Text style={styles.cardTitle}>가이드 빈도</Text><Text style={styles.freq}>{frequency}초</Text><View style={styles.adjust}>{[-30,-10,10,30].map(v=><Pressable accessibilityLabel={`가이드 빈도 ${v>0?`+${v}`:v}초`} key={v} onPress={()=>setFrequency(current=>Math.max(10,Math.min(300,current+v)))} style={({pressed})=>[styles.chip,pressed&&styles.chipPressed]}><Text style={styles.chipText}>{v>0?`+${v}`:v}</Text></Pressable>)}</View></View><View style={styles.guide}><Text style={styles.cardTitle}>러닝 가이드 방식</Text><Toggle label="음성 안내" copy="목표 이탈 시에만 짧게 코칭합니다" value={voiceEnabled} onChange={setVoiceEnabled}/><Toggle label="메트로놈 비트" copy="목표 SPM 리듬에 맞춘 박자 소리" value={metronomeEnabled} onChange={setMetronomeEnabled}/><Toggle label="진동 알림" copy="리듬 조절 필요 시 스마트폰 진동" value={hapticsEnabled} onChange={setHapticsEnabled}/></View></FigmaScreen>}
function Toggle({label,copy,value,onChange}:{label:string;copy:string;value:boolean;onChange:(v:boolean)=>void}){return <View style={styles.toggle}><View><Text style={styles.toggleLabel}>{label}</Text><Text style={styles.toggleCopy}>{copy}</Text></View><Switch value={value} onValueChange={onChange} trackColor={{false:'#DDE0E1',true:colors.primary}} thumbColor={colors.white}/></View>}
const styles=StyleSheet.create({header:{position:'absolute',top:navigationHeader.titleTop,alignSelf:'center',color:colors.white,fontSize:17,fontWeight:'700'},frequency:{position:'absolute',left:28,right:28,top:115-navigationHeader.contentLift,height:156,borderRadius:20,backgroundColor:colors.white,padding:22},cardTitle:{fontSize:17,fontWeight:'700',color:colors.ink},freq:{alignSelf:'center',fontSize:36,fontWeight:'800',color:colors.primary,marginTop:12},adjust:{position:'absolute',left:17,right:18,bottom:17,flexDirection:'row',justifyContent:'space-between'},chip:{width:54,height:34,borderWidth:1,borderColor:colors.border,borderRadius:14,alignItems:'center',justifyContent:'center'},chipPressed:compactPressFeedback,chipText:{fontSize:13,fontWeight:'700',color:colors.ink},guide:{position:'absolute',left:28,right:28,top:310-navigationHeader.contentLift,height:203,borderRadius:20,backgroundColor:colors.white,padding:21},toggle:{height:43,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingLeft:3},toggleLabel:{fontSize:15,fontWeight:'700',color:colors.ink},toggleCopy:{fontSize:12,color:'rgba(28,26,26,.58)',marginTop:2}});
