import { useLocalSearchParams, useRouter } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useCompleteOnboarding } from '@/src/api/queries';
import { useAuth } from '@/src/components/auth-provider';
import { FigmaBack, FigmaButton, FigmaLogo, FigmaScreen } from '@/src/components/figma-ui';
import { useOnboarding } from '@/src/components/onboarding-provider';
import { colors, pressFeedback } from '@/src/theme/tokens';
const cadenceControls = [
  { delta: -5, label: '-5' },
  { delta: -1, label: '−' },
  { delta: 1, label: '+' },
  { delta: 5, label: '+5' },
] as const;

export default function AdjustCadence(){const router=useRouter();const params=useLocalSearchParams<{recommended?:string}>();const{token,confirmOnboarded}=useAuth();const{draft,updateDraft}=useOnboarding();const recommendedValue=Number(params.recommended);const recommended=Number.isFinite(recommendedValue)?Math.max(130,Math.min(185,recommendedValue)):null;const[cadence,setCadence]=useState<number|null>(recommended);const mutation=useCompleteOnboarding(token);const finish=async()=>{if(cadence===null)return;try{const profile=await mutation.mutateAsync({runningPurpose:draft.purpose??'COMPLETE',experienceLevel:draft.experienceLevel??0,maxContinuousMin:draft.maxContinuousMin??10,weeklyGoalCount:draft.weeklyGoalCount??3,baselineCadence:cadence,heightCm:draft.heightCm,weightKg:draft.weightKg,birthYear:draft.birthYear,gender:draft.gender});updateDraft({baselineCadence:cadence});confirmOnboarded(profile.onboarded);router.replace('/');}catch{}};const adjust=(value:number)=>recommended===null?value:Math.max(130,recommended-10,Math.min(185,recommended+10,value));if(recommended===null||cadence===null)return <FigmaScreen><FigmaBack onPress={()=>router.back()}/><Text style={styles.missingTitle}>추천 리듬을 불러오지 못했어요</Text><Text style={styles.missingCopy}>이전 단계로 돌아가 다시 확인해 주세요.</Text></FigmaScreen>;return <FigmaScreen><FigmaBack onPress={()=>router.back()}/><FigmaLogo centered/><Text style={styles.title}>첫 러닝 리듬을 조정할 수 있어요</Text><Text style={styles.subtitle}>추천값에서 위아래로 10 spm까지 조정할 수 있어요</Text><View style={styles.card}><Text style={styles.cardTitle}>리듬 조절</Text><View style={styles.valueRow}><Text style={styles.value}>{cadence}</Text><Text style={styles.unit}>spm</Text></View><View style={styles.controls}>{cadenceControls.map(({delta,label})=><Pressable accessibilityLabel={`리듬 ${label}`} key={delta} onPress={()=>setCadence(c=>c===null?c:adjust(c+delta))} style={({pressed})=>[styles.control,pressed&&styles.controlPressed]}><Text style={styles.controlText}>{label}</Text></Pressable>)}</View></View><FigmaButton disabled={mutation.isPending} onPress={()=>void finish()} style={styles.button}>{mutation.isPending?'저장 중...':'시작하기'}</FigmaButton>{mutation.error?<Text style={styles.error}>정보를 저장하지 못했어요. 다시 시도해 주세요.</Text>:null}</FigmaScreen>}
const styles=StyleSheet.create({title:{position:'absolute',left:27,right:27,top:88,color:colors.white,fontSize:20,fontWeight:'800',textAlign:'center'},subtitle:{position:'absolute',left:27,right:27,top:122,color:colors.white,fontSize:14,textAlign:'center'},missingTitle:{position:'absolute',left:27,right:27,top:250,color:colors.white,fontSize:20,fontWeight:'800',textAlign:'center'},missingCopy:{position:'absolute',left:27,right:27,top:295,color:colors.textMuted,fontSize:14,textAlign:'center'},card:{position:'absolute',left:27,right:28,top:191,height:179,borderRadius:20,backgroundColor:colors.white,padding:18},cardTitle:{fontSize:17,fontWeight:'700',color:colors.ink},valueRow:{position:'absolute',left:0,right:0,top:60,flexDirection:'row',justifyContent:'center',alignItems:'center',gap:7},value:{fontSize:36,fontWeight:'800',color:colors.primary},unit:{fontSize:13,fontWeight:'700',color:colors.inkMuted,marginTop:14},controls:{position:'absolute',left:18,right:18,top:119,flexDirection:'row',justifyContent:'space-between'},control:{width:54,height:34,borderWidth:1,borderColor:colors.border,borderRadius:14,alignItems:'center',justifyContent:'center'},controlPressed:pressFeedback,controlText:{fontSize:13,fontWeight:'700',color:colors.ink},button:{top:583,backgroundColor:colors.primary},error:{position:'absolute',left:30,right:30,top:650,color:colors.danger,fontSize:12,textAlign:'center'}});
