import { useRouter } from 'expo-router';
import { StyleSheet, Text, View } from 'react-native';

import { useCompleteOnboarding } from '@/src/api/queries';
import { useAuth } from '@/src/components/auth-provider';
import { FigmaBack, FigmaButton, FigmaLogo, FigmaScreen } from '@/src/components/figma-ui';
import { useOnboarding } from '@/src/components/onboarding-provider';
import { computeInitialTargetCadence } from '@/src/engine/target';
import { colors } from '@/src/theme/tokens';

export default function CadenceScreen(){const router=useRouter();const{token,confirmOnboarded}=useAuth();const{draft,updateDraft}=useOnboarding();const mutation=useCompleteOnboarding(token);const cadence=draft.experienceLevel===undefined||draft.purpose===undefined?160:computeInitialTargetCadence(draft.experienceLevel,draft.purpose);
const finish=async()=>{try{const profile=await mutation.mutateAsync({runningPurpose:draft.purpose??'HABIT',experienceLevel:draft.experienceLevel??0,maxContinuousMin:draft.maxContinuousMin??5,weeklyGoalCount:draft.weeklyGoalCount??3,baselineCadence:cadence,heightCm:draft.heightCm,weightKg:draft.weightKg,birthYear:draft.birthYear,gender:draft.gender});updateDraft({baselineCadence:cadence});confirmOnboarded(profile.onboarded);router.replace('/');}catch{}};
return <FigmaScreen><FigmaBack onPress={()=>router.back()}/><FigmaLogo centered top={25}/><Text style={styles.title}>케이던스 측정이 끝났어요!</Text><Text style={styles.subtitle}>지금까지 알려주신 정보를 바탕으로{`\n`}케이던스를 추천해드릴게요</Text><View style={styles.card}><Text style={styles.cardTitle}>추천 케이던스</Text><View style={styles.valueRow}><Text style={styles.value}>{cadence}</Text><Text style={styles.unit}>SPM</Text></View><View style={styles.orangeLine}/><Text style={styles.cardCopy}>초보 러너에게 적합한 편안한 케이던스로{`\n`}달리와 함께 러닝을 시작해보세요</Text></View><View style={styles.reason}><Text style={styles.reasonTitle}>추천 이유</Text><Text style={styles.reasonStrong}>♧  왜 {cadence} SPM인가요?</Text><Text style={styles.reasonCopy}>러닝 경험과 목표 등 질문에 대한 바탕으로{`\n`}첫 러닝에 부담이 적은 케이던스를 추천했어요</Text></View><FigmaButton onPress={()=>void finish()} style={styles.primary}>추천 케이던스로 시작하기</FigmaButton><FigmaButton secondary onPress={()=>router.push('/onboarding/adjust')} style={styles.secondary}>케이던스 직접 조정하기</FigmaButton>{mutation.error?<Text style={styles.error}>정보를 저장하지 못했어요. 다시 시도해 주세요.</Text>:null}</FigmaScreen>}
const styles=StyleSheet.create({title:{position:'absolute',left:27,right:27,top:108,color:colors.white,fontSize:20,fontWeight:'800',textAlign:'center'},subtitle:{position:'absolute',left:27,right:27,top:143,color:colors.white,fontSize:14,lineHeight:20,textAlign:'center'},card:{position:'absolute',left:27,right:28,top:213,height:167,borderRadius:20,backgroundColor:colors.white,padding:18},cardTitle:{fontSize:17,fontWeight:'700',color:colors.ink},valueRow:{position:'absolute',top:55,left:0,right:0,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:7},value:{fontSize:36,fontWeight:'800',color:colors.primary},unit:{fontSize:13,fontWeight:'700',color:colors.inkMuted,marginTop:14},orangeLine:{position:'absolute',left:18,top:119,width:2,height:28,backgroundColor:colors.primary},cardCopy:{position:'absolute',left:27,top:116,color:colors.ink,fontSize:13,fontWeight:'700',lineHeight:18},reason:{position:'absolute',left:27,right:28,top:419,height:148,borderRadius:30,borderWidth:.5,borderColor:'rgba(221,224,225,0.5)',backgroundColor:'rgba(221,224,225,0.1)',padding:22},reasonTitle:{color:colors.white,fontSize:17,fontWeight:'700'},reasonStrong:{color:colors.white,fontSize:15,fontWeight:'700',marginTop:14},reasonCopy:{color:colors.white,fontSize:13,lineHeight:18,marginTop:10},primary:{top:602},secondary:{top:666},error:{position:'absolute',left:30,top:724,color:colors.danger,fontSize:12}});
