import { useRouter } from 'expo-router';
import { StyleSheet, Text, View } from 'react-native';

import { useCompleteOnboarding } from '@/src/api/queries';
import { useAuth } from '@/src/components/auth-provider';
import { FigmaBack, FigmaButton, FigmaLogo, FigmaScreen } from '@/src/components/figma-ui';
import { useOnboarding } from '@/src/components/onboarding-provider';
import { computeInitialTargetCadence } from '@/src/engine/target';
import { colors } from '@/src/theme/tokens';

export default function CadenceScreen(){const router=useRouter();const{token,confirmOnboarded}=useAuth();const{draft,updateDraft}=useOnboarding();const mutation=useCompleteOnboarding(token);const cadence=computeInitialTargetCadence(draft.experienceLevel??0,draft.purpose??'COMPLETE');
const finish=async()=>{try{const profile=await mutation.mutateAsync({runningPurpose:draft.purpose??'COMPLETE',experienceLevel:draft.experienceLevel??0,maxContinuousMin:draft.maxContinuousMin??10,weeklyGoalCount:draft.weeklyGoalCount??3,baselineCadence:cadence,heightCm:draft.heightCm,weightKg:draft.weightKg,birthYear:draft.birthYear,gender:draft.gender});updateDraft({baselineCadence:cadence});confirmOnboarded(profile.onboarded);router.replace('/');}catch{}};
return <FigmaScreen><FigmaBack onPress={()=>router.back()}/><FigmaLogo centered/><Text style={styles.title}>첫 러닝 리듬을 정했어요</Text><Text style={styles.subtitle}>지금까지 알려주신 정보를 바탕으로{`\n`}부담이 적은 리듬을 추천했어요</Text><View style={styles.card}><Text style={styles.cardTitle}>추천 리듬</Text><View style={styles.valueRow}><Text style={styles.value}>{cadence}</Text><Text style={styles.unit}>spm</Text></View><View style={styles.orangeLine}/><Text style={styles.cardCopy}>첫 러닝을 마치면 실제 기록으로{`\n`}나의 기준 리듬을 확인할 수 있어요</Text></View><View style={styles.reason}><Text style={styles.reasonTitle}>추천 이유</Text><Text style={styles.reasonStrong}>♧  왜 {cadence} spm인가요?</Text><Text style={styles.reasonCopy}>러닝 경험과 목표를 바탕으로{`\n`}첫 러닝에 부담이 적은 리듬을 추천했어요</Text></View><FigmaButton disabled={mutation.isPending} onPress={()=>void finish()} style={styles.primary}>{mutation.isPending?'저장 중...':'추천 리듬으로 시작하기'}</FigmaButton><FigmaButton secondary onPress={()=>router.push({pathname:'/onboarding/adjust',params:{recommended:String(cadence)}})} style={styles.secondary}>리듬 직접 조정하기</FigmaButton>{mutation.error?<Text style={styles.error}>정보를 저장하지 못했어요. 다시 시도해 주세요.</Text>:null}</FigmaScreen>}
const styles=StyleSheet.create({title:{position:'absolute',left:27,right:27,top:88,color:colors.white,fontSize:20,fontWeight:'800',textAlign:'center'},subtitle:{position:'absolute',left:27,right:27,top:123,color:colors.white,fontSize:14,lineHeight:20,textAlign:'center'},card:{position:'absolute',left:27,right:28,top:193,height:167,borderRadius:20,backgroundColor:colors.white,padding:18},cardTitle:{fontSize:17,fontWeight:'700',color:colors.ink},valueRow:{position:'absolute',top:55,left:0,right:0,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:7},value:{fontSize:36,fontWeight:'800',color:colors.primary},unit:{fontSize:13,fontWeight:'700',color:colors.inkMuted,marginTop:14},orangeLine:{position:'absolute',left:18,top:119,width:2,height:28,backgroundColor:colors.primary},cardCopy:{position:'absolute',left:27,top:116,color:colors.ink,fontSize:13,fontWeight:'700',lineHeight:18},reason:{position:'absolute',left:27,right:28,top:399,height:148,borderRadius:30,borderWidth:.5,borderColor:'rgba(221,224,225,0.5)',backgroundColor:'rgba(221,224,225,0.1)',padding:22},reasonTitle:{color:colors.white,fontSize:17,fontWeight:'700'},reasonStrong:{color:colors.white,fontSize:15,fontWeight:'700',marginTop:14},reasonCopy:{color:colors.white,fontSize:13,lineHeight:18,marginTop:10},primary:{top:582},secondary:{top:646},error:{position:'absolute',left:30,top:704,color:colors.danger,fontSize:12}});
