/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return API process liveness without touching external services.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/device": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate Device */
        post: operations["authenticate_device_auth_device_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Me */
        patch: operations["patch_me_users_me_patch"];
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Runs */
        get: operations["get_runs_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        /** Remove Run */
        delete: operations["remove_run_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Report */
        get: operations["read_report_runs__run_id__report_get"];
        put?: never;
        /** Create Report */
        post: operations["create_report_runs__run_id__report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plans */
        get: operations["get_plans_plans_get"];
        put?: never;
        /** Post Plan */
        post: operations["post_plan_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Plan */
        delete: operations["remove_plan_plans__plan_id__delete"];
        options?: never;
        head?: never;
        /** Patch Plan */
        patch: operations["patch_plan_plans__plan_id__patch"];
        trace?: never;
    };
    "/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calendar Month */
        get: operations["calendar_month_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppRunCreate */
        AppRunCreate: {
            /** Client Run Id */
            client_run_id: string;
            /** Plan Id */
            plan_id?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Duration Sec */
            duration_sec: number;
            /** Distance M */
            distance_m?: number | null;
            /** Condition */
            condition: number;
            /** Memo */
            memo?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source: "APP";
            /** Ended At */
            ended_at?: string | null;
            /**
             * Goal Type
             * @enum {string}
             */
            goal_type: "TIME" | "DISTANCE";
            /** Goal Value */
            goal_value: number;
            /** Target Cadence Min */
            target_cadence_min: number;
            /** Target Cadence Max */
            target_cadence_max: number;
            /** Final Target Min */
            final_target_min: number;
            /** Final Target Max */
            final_target_max: number;
            /** Avg Cadence */
            avg_cadence: number | null;
            /** Avg Pace Sec Per Km */
            avg_pace_sec_per_km?: number | null;
            /** Completed */
            completed: boolean;
            /** Intervention Count */
            intervention_count: number;
            /** Downshift Count */
            downshift_count: number;
            /** Samples */
            samples: components["schemas"]["RunSample"][];
            /** Events */
            events: components["schemas"]["RunEvent"][];
        };
        /** CalendarDayResponse */
        CalendarDayResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            plan: components["schemas"]["CalendarPlanResponse"] | null;
            /** Runs */
            runs: components["schemas"]["CalendarRunResponse"][];
        };
        /** CalendarPlanResponse */
        CalendarPlanResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PLANNED" | "DONE" | "SKIPPED";
            /**
             * Goal Type
             * @enum {string}
             */
            goal_type: "TIME" | "DISTANCE";
            /** Goal Value */
            goal_value: number;
        };
        /** CalendarResponse */
        CalendarResponse: {
            /** Days */
            days: components["schemas"]["CalendarDayResponse"][];
        };
        /** CalendarRunResponse */
        CalendarRunResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source
             * @enum {string}
             */
            source: "APP" | "MANUAL";
            /** Duration Sec */
            duration_sec: number;
            /** Completed */
            completed: boolean;
        };
        /** DeviceAuthRequest */
        DeviceAuthRequest: {
            /** Device Uuid */
            device_uuid: string;
        };
        /** DeviceAuthResponse */
        DeviceAuthResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /** Is New User */
            is_new_user: boolean;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            detail: components["schemas"]["ErrorDetail"];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** ManualRunCreate */
        ManualRunCreate: {
            /** Client Run Id */
            client_run_id: string;
            /** Plan Id */
            plan_id?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Duration Sec */
            duration_sec: number;
            /** Distance M */
            distance_m?: number | null;
            /** Condition */
            condition?: number | null;
            /** Memo */
            memo?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source: "MANUAL";
            /**
             * Completed
             * @default true
             * @constant
             */
            completed: true;
        };
        /** PlanCreate */
        PlanCreate: {
            /**
             * Planned Date
             * Format: date
             */
            planned_date: string;
            /**
             * Goal Type
             * @enum {string}
             */
            goal_type: "TIME" | "DISTANCE";
            /** Goal Value */
            goal_value: number;
            /** Memo */
            memo?: string | null;
        };
        /** PlanListResponse */
        PlanListResponse: {
            /** Items */
            items: components["schemas"]["PlanResponse"][];
        };
        /** PlanResponse */
        PlanResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Planned Date
             * Format: date
             */
            planned_date: string;
            /**
             * Goal Type
             * @enum {string}
             */
            goal_type: "TIME" | "DISTANCE";
            /** Goal Value */
            goal_value: number;
            /** Memo */
            memo: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "PLANNED" | "DONE" | "SKIPPED";
            /** Run Id */
            run_id: string | null;
        };
        /** PlanUpdate */
        PlanUpdate: {
            /**
             * Status
             * @enum {string}
             */
            status?: "PLANNED" | "DONE" | "SKIPPED";
            /**
             * Goal Type
             * @enum {string}
             */
            goal_type?: "TIME" | "DISTANCE";
            /** Goal Value */
            goal_value?: number;
        };
        /** RecentRunResponse */
        RecentRunResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Duration Sec */
            duration_sec: number;
            /** Completed */
            completed: boolean;
        };
        /** ReportMetricsResponse */
        ReportMetricsResponse: {
            /** Rhythm Score */
            rhythm_score: number | null;
            /** Late Drop Rate */
            late_drop_rate: number | null;
            /** Fatigue Index */
            fatigue_index: number | null;
            /** In Range Sec */
            in_range_sec: number | null;
        };
        /** ReportResponse */
        ReportResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Verdict */
            verdict: string;
            /** Evidence */
            evidence: string[];
            /** Hypothesis */
            hypothesis: string | null;
            /** Prescription */
            prescription: string | null;
            /** Next Goal Text */
            next_goal_text: string;
            /** Next Target Min */
            next_target_min: number;
            /** Next Target Max */
            next_target_max: number;
            /** Recovery Note */
            recovery_note: string | null;
            /** Limitation */
            limitation: string | null;
            metrics: components["schemas"]["ReportMetricsResponse"];
            /** Is Fallback */
            is_fallback: boolean;
            /** Model */
            model: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RunCreateResponse */
        RunCreateResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Client Run Id */
            client_run_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Analyzable */
            is_analyzable: boolean;
            /** Analysis Limitation */
            analysis_limitation: ("MANUAL_RUN" | "TOO_SHORT" | "INSUFFICIENT_SENSOR_DATA") | null;
            /** Rhythm Score */
            rhythm_score: number | null;
            /** Late Drop Rate */
            late_drop_rate: number | null;
            /** Fatigue Index */
            fatigue_index: number | null;
        };
        /** RunDetailResponse */
        RunDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Client Run Id */
            client_run_id: string;
            /**
             * Source
             * @enum {string}
             */
            source: "APP" | "MANUAL";
            /** Plan Id */
            plan_id: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Goal Type */
            goal_type: ("TIME" | "DISTANCE") | null;
            /** Goal Value */
            goal_value: number | null;
            /** Condition */
            condition: number | null;
            /** Target Cadence Min */
            target_cadence_min: number | null;
            /** Target Cadence Max */
            target_cadence_max: number | null;
            /** Final Target Min */
            final_target_min: number | null;
            /** Final Target Max */
            final_target_max: number | null;
            /** Duration Sec */
            duration_sec: number;
            /** Distance M */
            distance_m: number | null;
            /** Avg Cadence */
            avg_cadence: number | null;
            /** Avg Pace Sec Per Km */
            avg_pace_sec_per_km: number | null;
            /** Completed */
            completed: boolean;
            /** Rhythm Score */
            rhythm_score: number | null;
            /** Late Drop Rate */
            late_drop_rate: number | null;
            /** Fatigue Index */
            fatigue_index: number | null;
            /** Intervention Count */
            intervention_count: number | null;
            /** Downshift Count */
            downshift_count: number | null;
            /** Memo */
            memo: string | null;
            /** Is Analyzable */
            is_analyzable: boolean;
            /** Analysis Limitation */
            analysis_limitation: ("MANUAL_RUN" | "TOO_SHORT" | "INSUFFICIENT_SENSOR_DATA") | null;
            /** Samples */
            samples: components["schemas"]["RunSample"][] | null;
            /** Events */
            events: components["schemas"]["RunEvent"][] | null;
            report: components["schemas"]["ReportResponse"] | null;
        };
        /** RunEvent */
        RunEvent: {
            /** T */
            t: number;
            /**
             * Type
             * @enum {string}
             */
            type: "RUN_START" | "TOO_FAST" | "TOO_SLOW" | "TARGET_ADJUSTED" | "RECOVERY_MODE_ON" | "PAUSE" | "RESUME" | "RUN_END";
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /** RunListItem */
        RunListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Duration Sec */
            duration_sec: number;
            /** Distance M */
            distance_m: number | null;
            /** Avg Cadence */
            avg_cadence: number | null;
            /** Completed */
            completed: boolean;
            /**
             * Source
             * @enum {string}
             */
            source: "APP" | "MANUAL";
            /** Rhythm Score */
            rhythm_score: number | null;
            /** Has Report */
            has_report: boolean;
        };
        /** RunListResponse */
        RunListResponse: {
            /** Items */
            items: components["schemas"]["RunListItem"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** RunSample */
        RunSample: {
            /** T */
            t: number;
            /** C */
            c: number;
            /** P */
            p?: number | null;
            /** D */
            d?: number | null;
        };
        /** StatsResponse */
        StatsResponse: {
            /** Total Run Days */
            total_run_days: number;
            /** Dalli Days */
            dalli_days: number;
            /** This Month Days */
            this_month_days: number;
            /** This Week Count */
            this_week_count: number;
            /** Next Milestone */
            next_milestone: number;
            recent_run: components["schemas"]["RecentRunResponse"] | null;
        };
        /** UserMeResponse */
        UserMeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Onboarded */
            onboarded: boolean;
            /** Running Purpose */
            running_purpose: ("COMPLETE" | "HABIT" | "WEIGHT" | "FITNESS" | "PERFORMANCE") | null;
            /** Experience Level */
            experience_level: number | null;
            /** Max Continuous Min */
            max_continuous_min: number | null;
            /** Weekly Goal Count */
            weekly_goal_count: number | null;
            /** Baseline Cadence */
            baseline_cadence: number | null;
            /** Height Cm */
            height_cm: number | null;
            /** Weight Kg */
            weight_kg: number | null;
            /** Birth Year */
            birth_year: number | null;
            /** Gender */
            gender: ("M" | "F" | "O") | null;
        };
        /** UserMeUpdate */
        UserMeUpdate: {
            /** Running Purpose */
            running_purpose?: ("COMPLETE" | "HABIT" | "WEIGHT" | "FITNESS" | "PERFORMANCE") | null;
            /** Experience Level */
            experience_level?: number | null;
            /** Max Continuous Min */
            max_continuous_min?: number | null;
            /** Weekly Goal Count */
            weekly_goal_count?: number | null;
            /** Baseline Cadence */
            baseline_cadence?: number | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Weight Kg */
            weight_kg?: number | string | null;
            /** Birth Year */
            birth_year?: number | null;
            /** Gender */
            gender?: ("M" | "F" | "O") | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    authenticate_device_auth_device_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceAuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceAuthResponse"];
                };
            };
            /** @description 요청 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_me_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patch_me_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserMeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 요청 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_runs_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description query 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_run_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppRunCreate"] | components["schemas"]["ManualRunCreate"];
            };
        };
        responses: {
            /** @description 멱등 재요청 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreateResponse"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreateResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 계획 없음 또는 소유권 불일치 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 계획 연결 충돌 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 요청 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 러닝 없음 또는 소유권 불일치 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description path 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    remove_run_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 러닝 없음 또는 소유권 불일치 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description path 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_report_runs__run_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 러닝 또는 리포트 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description path 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_report_runs__run_id__report_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 생성 또는 기존 리포트 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 러닝 없음 또는 소유권 불일치 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 수기 러닝 또는 잘못된 목표 범위 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_plans_plans_get: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanListResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description query 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_plan_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 같은 날짜 계획 충돌 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 요청 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    remove_plan_plans__plan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 계획 없음 또는 소유권 불일치 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description path 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patch_plan_plans__plan_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 계획 없음 또는 소유권 불일치 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 요청 또는 path 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    calendar_month_calendar_get: {
        parameters: {
            query: {
                year: number;
                month: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description query 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stats_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
